export const ALL_ORDERS = 'ALL_ORDERS';
export const ALL_ORDERS_SUCCESS = 'ALL_ORDERS_SUCCESS';
export const CHANGE_STATUS_ORDER = 'CHANGE_STATUS_ORDER';
export const SELECT_ORDER = 'SELECT_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';
export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';

export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';

export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';

export const ADD_ORDER_ITEM = 'ADD_ORDER_ITEM';
