export const ALL_CUSTOMERS = 'ALL_CUSTOMERS';
export const ALL_CUSTOMERS_SUCCESS = 'ALL_CUSTOMERS_SUCCESS';

export const CHANGE_STATUS_CUSTOMER = 'CHANGE_STATUS_CUSTOMER';
export const SELECT_CUSTOMER = 'SELECT_CUSTOMER';

export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';

export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';

export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';

export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
