export const ALL_CATEGORYS = 'ALL_CATEGORYS';
export const ALL_CATEGORYS_SUCCESS = 'ALL_CATEGORYS_SUCCESS';
export const CHANGE_STATUS_CATEGORY = 'CHANGE_STATUS_CATEGORY';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';

export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
