export const ALL_QUOTES = "ALL_QUOTES";
export const ALL_QUOTES_SUCCESS = "ALL_QUOTES_SUCCESS";
export const CHANGE_STATUS_QUOTE = "CHANGE_STATUS_QUOTE";
export const SELECT_QUOTE = "SELECT_QUOTE";
export const REMOVE_QUOTE = "REMOVE_QUOTE";
export const ADD_QUOTE = "ADD_QUOTE";
export const ADD_QUOTE_SUCCESS = "ADD_QUOTE_SUCCESS";

export const UPDATE_QUOTE = "UPDATE_QUOTE";

export const UPDATE_QUOTE_SUCCESS = "UPDATE_QUOTE_SUCCESS";

export const DELETE_QUOTE_SUCCESS = "DELETE_QUOTE_SUCCESS";

export const ADD_QUOTE_ITEM = "ADD_QUOTE_ITEM";

export const CHANGE_ITEM = "CHANGE_ITEM";

export const REMOVE_ITEM = "REMOVE_ITEM";

export const UPDATE_QTY_ITEM = "UPDATE_QTY_ITEM";

export const UPDATE_QUOTE_TOTAL = "UPDATE_QUOTE_TOTAL";

export const UPDATE_ITEM_TOTAL = "UPDATE_ITEM_TOTAL";

export const SELECT_CUSTOMER = "SELECT_CUSTOMER";

export const INCREATE_QTY_ITEM = "INCREATE_QTY_ITEM";

export const DECREATE_QUOTE_ITEM = "DECREATE_QUOTE_ITEM";

export const DISCOUNT = "DISCOUNT";
